### ISSUE TITLE
Use with Prokka gff

### ISSUE THREAD

**Issue by ohickl** [alejandrogzi/gxf2bed#2]
Hey,
the tool looks very nice!
I would like to use it with gff files coming from [Prokka](https://github.com/tseemann/prokka) but I might have trouble setting the `--parent/--child` parameters properly.
I need to capture all the different fields in the `Type` column of the gff in my bed output and the gffs dont have `parent/child` in the attribute field:
```
contig1	Prodigal_v2.6.3	CDS	362	721	.	-	0	ID=id_a;...
contig2	Aragorn:001002	tRNA	16	92	.	+	.	ID=id_b;...
contig3	minced:0.4.2	repeat_region	1982	2385	.	.	.	ID=id_c;...
contig4	barrnap:0.9	rRNA	2	1350	2.2e-290	-	.	ID=id_d;...
...
```
Is this supported?

Just calling e.g.:
```
gxf2bed --input ${gff} \
        --output ${bed} \
        --feature "ID" \
        --threads 8
```
doesn't throw an error but leads to an empty output (same as when setting `--parent` and `--child` to `""` or `"ID"`):
```
##### GXF2BED #####
Fastest GTF/GFF-to-BED converter chilling around.
Repository: https://github.com/alejandrogzi/gxf2bed
Feel free to contact the developer if any issue/bug is found.
Version: 0.2.1

2024-03-20T08:54:17.693Z INFO  [gxf2bed] Args { gxf: ".../test.gff", output: ".../test.bed", threads: 8, parent: "transcript", child: "exon", feature: "ID" }
2024-03-20T08:54:17.693Z INFO  [gxf2bed] Using 8 threads
2024-03-20T08:54:17.694Z INFO  [gxf2bed] 21 records parsed
2024-03-20T08:54:17.695Z INFO  [gxf2bed::utils] Writing to "../test.bed"
2024-03-20T08:54:17.695Z INFO  [gxf2bed::utils] Done writing!
2024-03-20T08:54:17.695Z INFO  [gxf2bed] Elapsed: 0.0021 secs
2024-03-20T08:54:17.695Z INFO  [gxf2bed] Memory: 0.00 MB
```

setting `--parent` to e.g. `"CDS"` results in:
```
...
thread 'main' panicked at /opt/conda/conda-bld/gxf2bed_1709011218863/work/src/utils.rs:42:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Best

Oskar

**Comment by alejandrogzi** [comment]
Hi @ohickl,

Sorry for the delay response and thank for using gxf2bed! 

> Is this supported?

I do not think so. The intended usage was build based (but not exclusive) on other "type" of G{T,F}Fs, such as Ensembl or GENCODE. The empty output is the result of not finding any relationship between your arguments.

Could you please share your file? I will try to produce a new version that could satisfy your needs.

Best,
Alejandro

**Comment by ohickl** [comment]
Sure, will this example work? It has the 4 different kinds of features the files can contain.
Thanks for taking the time!
[test.gff.zip](https://github.com/alejandrogzi/gxf2bed/files/14707240/test.gff.zip)

**Comment by alejandrogzi** [comment]
@ohickl 

Thanks for your file and sorry again for the wait. Please can you confirm that this output will satisfy your needs?

```
contig_01       2       422     gene_01 0       -       2       422     0       1       420,    0,
contig_02       0       852     gene_02 0       -       0       852     0       1       852,    0,
contig_03       450     524     gene_03 0       -       450     524     0       1       74,     0,
contig_04       1       433     CRISPR_01       0       .       1       433     0       1       432,    0,
```

To only translate the file without any parent-child relationship now you will just need to specify: 

```
gxf2bed --input ${gff} \
        --output ${bed} \
        --parent "" \
        --child "" \
        --feature "ID" \
        --threads 8
```

explicitly indicating that no relationship should be inferred. I will wait your confirmation to proceed to push the changes and publish the new verion.

Best,
Alejandro

**Comment by ohickl** [comment]
Looks good!
Thanks a lot!

**Comment by alejandrogzi** [comment]
Nice to hear that! The new version is already available through crate and docker, wil take 1-2 days to be available from conda. 

Thank you for your feedback and ideas, let me know if you have more!

Best,
Alejandro
